CREATE TABLE [dl].[DimTeam] (
    [TeamID]                                   INT            NOT NULL,
    [TeamCode]                                 NVARCHAR (10)  NULL,
    [TeamName]                                 NVARCHAR (100) NULL,
    [TeamDescription]                          NVARCHAR (MAX) NULL,
    [CompanyID]                                INT            NOT NULL,
    [ContractID]                               INT            NULL,
    [TeamFunctionID]                           INT            NOT NULL,
    [TeamAutoAccept]                           BIT            NOT NULL,
    [TeamCapacity]                             INT            NULL,
    [AreaID]                                   INT            NOT NULL,
    [TeamStartDate]                            DATETIME       NULL,
    [TeamEndDate]                              DATETIME       NULL,
    [OldTeamID]                                INT            NULL,
    [OldSupportLevelID]                        INT            NULL,
    [TeamUDF1]                                 NVARCHAR (MAX) NULL,
    [TeamUDF2]                                 NVARCHAR (MAX) NULL,
    [TeamUDF3]                                 NVARCHAR (MAX) NULL,
    [TeamUDF4]                                 NVARCHAR (MAX) NULL,
    [TeamUDF5]                                 NVARCHAR (MAX) NULL,
    [TeamUDF6]                                 NVARCHAR (MAX) NULL,
    [TeamUDF7]                                 NVARCHAR (MAX) NULL,
    [TeamUDF8]                                 NVARCHAR (MAX) NULL,
    [TeamUDF9]                                 NVARCHAR (MAX) NULL,
    [TeamUDF10]                                NVARCHAR (MAX) NULL,
    [TeamLUDF1]                                INT            NULL,
    [TeamLUDF2]                                INT            NULL,
    [TeamLUDF3]                                INT            NULL,
    [TeamLUDF4]                                INT            NULL,
    [TeamLUDF5]                                INT            NULL,
    [TeamRecentlyDischargedPeriodDaysOverride] INT            NULL,
    [SupportLevelTypeID]                       INT            NULL,
    [TaskProcessID]                            INT            NULL,
    [TeamIsEmploymentTeam]                     BIT            NOT NULL,
    [EmploymentPlanTemplateID]                 INT            NULL,
    [TeamIsAllocatedSupportTimeTeam]           BIT            NOT NULL,
    [TeamReferenceNumberRequired]              BIT            NOT NULL,
    [TeamIsFosterCarerTeam]                    BIT            NOT NULL,
    [TeamIsFosterChildTeam]                    BIT            NOT NULL,
    [DynamicFormID]                            INT            NULL,
    [TeamShowGlobalActivityTemplate]           BIT            NOT NULL,
    CONSTRAINT [PK_dl_DimTeam] PRIMARY KEY CLUSTERED ([TeamID] ASC)
);


GO

