CREATE TABLE [stage].[Stage_Team] (
    [ID]                                   INT            NOT NULL,
    [Code]                                 NVARCHAR (10)  NULL,
    [Name]                                 NVARCHAR (100) NULL,
    [Description]                          NVARCHAR (MAX) NULL,
    [CompanyID]                            INT            NOT NULL,
    [ContractID]                           INT            NULL,
    [TeamFunctionID]                       INT            NOT NULL,
    [AutoAccept]                           BIT            NOT NULL,
    [Capacity]                             INT            NULL,
    [AreaID]                               INT            NOT NULL,
    [StartDate]                            DATETIME       NULL,
    [EndDate]                              DATETIME       NULL,
    [OldTeamID]                            INT            NULL,
    [OldSupportLevelID]                    INT            NULL,
    [UDF1]                                 NVARCHAR (MAX) NULL,
    [UDF2]                                 NVARCHAR (MAX) NULL,
    [UDF3]                                 NVARCHAR (MAX) NULL,
    [UDF4]                                 NVARCHAR (MAX) NULL,
    [UDF5]                                 NVARCHAR (MAX) NULL,
    [UDF6]                                 NVARCHAR (MAX) NULL,
    [UDF7]                                 NVARCHAR (MAX) NULL,
    [UDF8]                                 NVARCHAR (MAX) NULL,
    [UDF9]                                 NVARCHAR (MAX) NULL,
    [UDF10]                                NVARCHAR (MAX) NULL,
    [LUDF1]                                INT            NULL,
    [LUDF2]                                INT            NULL,
    [LUDF3]                                INT            NULL,
    [LUDF4]                                INT            NULL,
    [LUDF5]                                INT            NULL,
    [RecentlyDischargedPeriodDaysOverride] INT            NULL,
    [InactiveUserID]                       INT            NULL,
    [InactiveDate]                         DATETIME       NULL,
    [CreatedUserID]                        INT            NOT NULL,
    [CreatedDate]                          DATETIME       NOT NULL,
    [ModifiedUserID]                       INT            NULL,
    [ModifiedDate]                         DATETIME       NULL,
    [DeletedUserID]                        INT            NULL,
    [DeletedDate]                          DATETIME       NULL,
    [SupportLevelTypeID]                   INT            NULL,
    [TaskProcessID]                        INT            NULL,
    [IsEmploymentTeam]                     BIT            NOT NULL,
    [EmploymentPlanTemplateID]             INT            NULL,
    [IsAllocatedSupportTimeTeam]           BIT            NOT NULL,
    [ReferenceNumberRequired]              BIT            NOT NULL,
    [IsFosterCarerTeam]                    BIT            NOT NULL,
    [IsFosterChildTeam]                    BIT            NOT NULL,
    [DynamicFormID]                        INT            NULL,
    [ShowGlobalActivityTemplate]           BIT            NOT NULL
);


GO

