CREATE TABLE [stage].[Stage_Account] (
    [ID]                     INT            NOT NULL,
    [Name]                   NVARCHAR (300) NOT NULL,
    [Location]               NVARCHAR (200) NULL,
    [DescriptionHTML]        NVARCHAR (MAX) NULL,
    [DescriptionRaw]         NVARCHAR (MAX) NULL,
    [IndustryTypeID]         INT            NOT NULL,
    [AccountOwnerUserID]     INT            NOT NULL,
    [PostalAddressLine1]     NVARCHAR (200) NOT NULL,
    [PostalAddressLine2]     NVARCHAR (200) NULL,
    [PostalAddressSuburb]    NVARCHAR (100) NULL,
    [PostalAddressCity]      NVARCHAR (100) NOT NULL,
    [PostalAddressPostCode]  NVARCHAR (100) NULL,
    [PostalAddressCountryID] INT            NULL,
    [StreetAddressLine1]     NVARCHAR (200) NOT NULL,
    [StreetAddressLine2]     NVARCHAR (200) NULL,
    [StreetAddressSuburb]    NVARCHAR (100) NULL,
    [StreetAddressCity]      NVARCHAR (100) NOT NULL,
    [RegionID]               INT            NOT NULL,
    [StreetAddressCountryID] INT            NOT NULL,
    [Phone]                  NVARCHAR (50)  NULL,
    [AlternativePhone]       NVARCHAR (50)  NULL,
    [Fax]                    NVARCHAR (50)  NULL,
    [WebsiteAddress]         NVARCHAR (100) NULL,
    [PrimaryEmailAddress]    NVARCHAR (100) NULL,
    [CreatedDate]            DATETIME       NOT NULL,
    [CreatedUserID]          INT            NOT NULL,
    [ModifiedDate]           DATETIME       NULL,
    [ModifiedUserID]         INT            NULL,
    [DeletedDate]            DATETIME       NULL,
    [DeletedUserID]          INT            NULL,
    [UDF1]                   NVARCHAR (MAX) NULL,
    [UDF2]                   NVARCHAR (MAX) NULL,
    [UDF3]                   NVARCHAR (MAX) NULL,
    [UDF4]                   NVARCHAR (MAX) NULL,
    [UDF5]                   NVARCHAR (MAX) NULL,
    [IsEmployer]             BIT            NOT NULL,
    [PrimaryContactID]       INT            NULL,
    [CompanyId]              INT            NOT NULL
);


GO

