CREATE TABLE [stage].[Stage_Person] (
    [ID]                                          INT            NOT NULL,
    [TitleID]                                     INT            NULL,
    [FirstName]                                   NVARCHAR (255) NOT NULL,
    [MiddleNames]                                 NVARCHAR (255) NULL,
    [LastName]                                    NVARCHAR (255) NOT NULL,
    [PreferredName]                               NVARCHAR (255) NULL,
    [MaidenName]                                  NVARCHAR (255) NULL,
    [DateOfBirth]                                 DATE           NOT NULL,
    [GenderID]                                    INT            NOT NULL,
    [OldClientID]                                 INT            NULL,
    [MaritalStatusID]                             INT            NULL,
    [HighestQualificationTypeID]                  INT            NULL,
    [ReligionID]                                  INT            NULL,
    [ResidencyID]                                 INT            NULL,
    [NationalityID]                               INT            NULL,
    [CountryOfBirthID]                            INT            NULL,
    [PrimaryDailyActivityID]                      INT            NULL,
    [DeceasedDate]                                DATETIME       NULL,
    [Occupation]                                  NVARCHAR (50)  NULL,
    [DriversLicenceNumber]                        NVARCHAR (15)  NULL,
    [DriversLicenceExpiry]                        DATETIME       NULL,
    [PrimaryTransportID]                          INT            NULL,
    [VehicleRegistrationNumber]                   NVARCHAR (10)  NULL,
    [VehicleMakeAndModel]                         NVARCHAR (30)  NULL,
    [VehicleColor]                                NVARCHAR (20)  NULL,
    [VehicleDescription]                          NVARCHAR (MAX) NULL,
    [PhysicalDescription]                         NVARCHAR (MAX) NULL,
    [CulturalNeeds]                               NVARCHAR (MAX) NULL,
    [SpiritualNeeds]                              NVARCHAR (MAX) NULL,
    [Height]                                      NVARCHAR (50)  NULL,
    [Weight]                                      NVARCHAR (50)  NULL,
    [Build]                                       NVARCHAR (50)  NULL,
    [EyeColor]                                    NVARCHAR (50)  NULL,
    [HairColor]                                   NVARCHAR (50)  NULL,
    [HairStyle]                                   NVARCHAR (50)  NULL,
    [EducationalActivityTypeID]                   INT            NULL,
    [EducationalActivityHoursPerWeek]             DECIMAL (6, 2) NULL,
    [EducationBackground]                         NVARCHAR (MAX) NULL,
    [CaresForOtherFamilyMembers]                  BIT            NULL,
    [CaresForOtherFamilyMembersReason]            NVARCHAR (MAX) NULL,
    [FamilyBackground]                            NVARCHAR (MAX) NULL,
    [EmploymentStatusID]                          INT            NULL,
    [EmploymentStatusHoursPerWeek]                DECIMAL (6, 2) NULL,
    [EmploymentHistoryID]                         INT            NULL,
    [LastEmploymentDate]                          DATETIME       NULL,
    [EmploymentBackground]                        NVARCHAR (MAX) NULL,
    [ReferenceNumber]                             NVARCHAR (50)  NULL,
    [UDF1]                                        NVARCHAR (MAX) NULL,
    [UDF2]                                        NVARCHAR (MAX) NULL,
    [UDF3]                                        NVARCHAR (MAX) NULL,
    [UDF4]                                        NVARCHAR (MAX) NULL,
    [UDF5]                                        NVARCHAR (MAX) NULL,
    [SocialBackground]                            NVARCHAR (MAX) NULL,
    [TreatmentBackground]                         NVARCHAR (MAX) NULL,
    [LivingSituationID]                           INT            NULL,
    [CreatedDate]                                 DATETIME       NOT NULL,
    [CreatedUserID]                               INT            NOT NULL,
    [ModifiedDate]                                DATETIME       NULL,
    [ModifiedUserID]                              INT            NULL,
    [DeletedDate]                                 DATETIME       NULL,
    [DeletedUserID]                               INT            NULL,
    [ServiceUserConsent]                          BIT            NOT NULL,
    [PrimaryCarerID]                              INT            NULL,
    [Ethnicity1ID]                                INT            NULL,
    [Ethnicity2ID]                                INT            NULL,
    [Ethnicity3ID]                                INT            NULL,
    [Ethnicity4ID]                                INT            NULL,
    [Ethnicity5ID]                                INT            NULL,
    [IsPrivate]                                   BIT            NOT NULL,
    [FosterChildrenCapacity]                      INT            NULL,
    [PreferedFosterCareService]                   VARCHAR (12)   NULL,
    [MadePrivateOrPublicReason]                   NVARCHAR (MAX) NULL,
    [MadePrivateOrPublicDate]                     DATETIME2 (7)  NULL,
    [MadePrivateOrPublicUserId]                   INT            NULL,
    [GenderIdentityId]                            INT            NULL,
    [PronounsId]                                  INT            NULL,
    [AnotherGender]                               NVARCHAR (MAX) NULL,
    [AnotherPronoun]                              NVARCHAR (MAX) NULL,
    [AnotherGenderIdentity]                       NVARCHAR (MAX) NULL,
    [IsIwiAffiliationKnown]                       BIT            NULL,
    [DoesPersonWantToKnowMoreAboutIwiAffiliation] BIT            NULL,
    [Marae]                                       NVARCHAR (MAX) NULL,
    [WhanauName]                                  NVARCHAR (MAX) NULL,
    [Pepeha]                                      NVARCHAR (MAX) NULL
);


GO

