CREATE TABLE [legacy].[DimClient] (
    [ID]                                          INT            NOT NULL,
    [TitleID]                                     INT            NULL,
    [FirstName]                                   NVARCHAR (255) NOT NULL,
    [MiddleNames]                                 NVARCHAR (255) NULL,
    [LastName]                                    NVARCHAR (255) NOT NULL,
    [PreferredName]                               NVARCHAR (255) NULL,
    [MaidenName]                                  NVARCHAR (255) NULL,
    [DateOfBirth]                                 DATE           NOT NULL,
    [GenderID]                                    INT            NOT NULL,
    [OldClientID]                                 INT            NULL,
    [MaritalStatusID]                             INT            NULL,
    [HighestQualificationTypeID]                  INT            NULL,
    [ReligionID]                                  INT            NULL,
    [ResidencyID]                                 INT            NULL,
    [NationalityID]                               INT            NULL,
    [CountryOfBirthID]                            INT            NULL,
    [PrimaryDailyActivityID]                      INT            NULL,
    [LivingSituationID]                           INT            NULL,
    [DeceasedDate]                                DATETIME       NULL,
    [Occupation]                                  NVARCHAR (50)  NULL,
    [DriversLicenceNumber]                        NVARCHAR (15)  NULL,
    [DriversLicenceExpiry]                        DATETIME       NULL,
    [PrimaryTransportID]                          INT            NULL,
    [VehicleRegistrationNumber]                   NVARCHAR (10)  NULL,
    [VehicleMakeAndModel]                         NVARCHAR (30)  NULL,
    [VehicleColor]                                NVARCHAR (20)  NULL,
    [VehicleDescription]                          NVARCHAR (MAX) NULL,
    [PhysicalDescription]                         NVARCHAR (MAX) NULL,
    [CulturalNeeds]                               NVARCHAR (MAX) NULL,
    [SpiritualNeeds]                              NVARCHAR (MAX) NULL,
    [Height]                                      NVARCHAR (50)  NULL,
    [Weight]                                      NVARCHAR (50)  NULL,
    [Build]                                       NVARCHAR (50)  NULL,
    [EyeColor]                                    NVARCHAR (50)  NULL,
    [HairColor]                                   NVARCHAR (50)  NULL,
    [HairStyle]                                   NVARCHAR (50)  NULL,
    [EducationalActivityTypeID]                   INT            NULL,
    [EducationalActivityHoursPerWeek]             DECIMAL (6, 2) NULL,
    [EducationBackground]                         NVARCHAR (MAX) NULL,
    [CaresForOtherFamilyMembers]                  BIT            NULL,
    [CaresForOtherFamilyMembersReason]            NVARCHAR (MAX) NULL,
    [FamilyBackground]                            NVARCHAR (MAX) NULL,
    [EmploymentStatusID]                          INT            NULL,
    [EmploymentStatusHoursPerWeek]                DECIMAL (6, 2) NULL,
    [EmploymentHistoryID]                         INT            NULL,
    [LastEmploymentDate]                          DATETIME       NULL,
    [EmploymentBackground]                        NVARCHAR (MAX) NULL,
    [ReferenceNumber]                             NVARCHAR (50)  NULL,
    [SocialBackground]                            NVARCHAR (MAX) NULL,
    [TreatmentBackground]                         NVARCHAR (MAX) NULL,
    [FullName]                                    NVARCHAR (512) NULL,
    [AddressLine1]                                NVARCHAR (200) NULL,
    [AddressLine2]                                NVARCHAR (200) NULL,
    [AddressLine3]                                NVARCHAR (200) NULL,
    [AddressTownCity]                             NVARCHAR (50)  NULL,
    [AddressSuburb]                               NVARCHAR (100) NULL,
    [AddressStateID]                              INT            NULL,
    [AddressCountryID]                            INT            NULL,
    [AddressPostCode]                             NVARCHAR (50)  NULL,
    [Ethnicity1]                                  INT            NULL,
    [Ethnicity2]                                  INT            NULL,
    [Ethnicity3]                                  INT            NULL,
    [IsCurrent]                                   VARCHAR (5)    NOT NULL,
    [Substance1]                                  INT            NULL,
    [Substance2]                                  INT            NULL,
    [Substance3]                                  INT            NULL,
    [PhysicalHealthCondition1]                    INT            NULL,
    [PhysicalHealthCondition2]                    INT            NULL,
    [PhysicalHealthCondition3]                    INT            NULL,
    [MentalHealthCondition1]                      INT            NULL,
    [MentalHealthCondition2]                      INT            NULL,
    [MentalHealthCondition3]                      INT            NULL,
    [PhoneNumbers]                                NVARCHAR (MAX) NULL,
    [EmailAddresses]                              NVARCHAR (MAX) NULL,
    [ServiceUserConsent]                          BIT            NOT NULL,
    [FosterChildrenCapacity]                      INT            NULL,
    [PreferedFosterCareService]                   NVARCHAR (50)  NULL,
    [CurrentPhysicalHealthConditions]             NVARCHAR (MAX) NULL,
    [HistoricPhysicalHealthConditions]            NVARCHAR (MAX) NULL,
    [CurrentMentalHealthConditions]               NVARCHAR (MAX) NULL,
    [HistoricMentalHealthConditions]              NVARCHAR (MAX) NULL,
    [CurrentSubstances]                           NVARCHAR (MAX) NULL,
    [HistoricSubstances]                          NVARCHAR (MAX) NULL,
    [AddressName]                                 NVARCHAR (50)  NULL,
    [AnotherGender]                               NVARCHAR (MAX) NULL,
    [GenderIdentityID]                            INT            NULL,
    [AnotherPronoun]                              NVARCHAR (MAX) NULL,
    [AnotherGenderIdentity]                       NVARCHAR (MAX) NULL,
    [Ethnicity4]                                  INT            NULL,
    [Ethnicity5]                                  INT            NULL,
    [IsIwiAffiliationKnown]                       BIT            NULL,
    [DoesPersonWantToKnowMoreAboutIwiAffiliation] BIT            NULL,
    [Marae]                                       NVARCHAR (MAX) NULL,
    [WhanauName]                                  NVARCHAR (MAX) NULL,
    [Pepeha]                                      NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_legacy_DimClient] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

