
CREATE VIEW [sf].[vw_anonym_DimPerson]
as
SELECT dp.PersonID, 
dp.TitleID, 
'PersonFirstName for ' + cast( dp.PersonID as nvarchar)      AS PersonFirstName     ,
'PersonMiddleNames for ' + cast( dp.PersonID as nvarchar)    AS PersonMiddleNames   ,
'PersonLastName for ' + cast( dp.PersonID as nvarchar)       AS PersonLastName      ,
'PersonPreferredName for ' + cast( dp.PersonID as nvarchar)  AS PersonPreferredName ,
'PersonMaidenName for ' + cast( dp.PersonID as nvarchar)     AS PersonMaidenName    ,
GetDate()    AS PersonDateOfBirth,
dp.GenderID, 
dp.OldClientID, 
dp.MaritalStatusID, 
dp.HighestQualificationTypeID, 
dp.ReligionID, 
dp.ResidencyID, 
dp.NationalityID, 
dp.CountryOfBirthID, 
dp.PrimaryDailyActivityID, 
dp.PersonDeceasedDate, 
dp.PersonOccupation, 
'PersonDriversLicenceNumber for ' + cast( dp.PersonID as nvarchar)     AS PersonDriversLicenceNumber, 
GetDate()    AS PersonDriversLicenceExpiry, 
dp.PrimaryTransportID, 
'PersonVehicleRegistrationNumber for ' + cast( dp.PersonID as nvarchar)     AS PersonVehicleRegistrationNumber, 
dp.PersonVehicleMakeAndModel, 
dp.PersonVehicleColor, 
'PersonVehicleDescription for ' + cast( dp.PersonID as nvarchar)     AS PersonVehicleDescription, 
'PersonPhysicalDescription for ' + cast( dp.PersonID as nvarchar)     AS PersonPhysicalDescription, 
'PersonCulturalNeeds for ' + cast( dp.PersonID as nvarchar)     AS PersonCulturalNeeds, 
'PersonSpiritualNeeds for ' + cast( dp.PersonID as nvarchar)     AS PersonSpiritualNeeds, 
dp.PersonHeight, 
dp.PersonWeight, 
dp.PersonBuild, 
dp.PersonEyeColor, 
dp.PersonHairColor, 
dp.PersonHairStyle, 
dp.EducationalActivityTypeID, 
dp.PersonEducationalActivityHoursPerWeek, 
'PersonEducationBackground for ' + cast( dp.PersonID as nvarchar)     AS PersonEducationBackground, 
dp.PersonCaresForOtherFamilyMembers, 
'PersonCaresForOtherFamilyMembersReason for ' + cast( dp.PersonID as nvarchar)     AS PersonCaresForOtherFamilyMembersReason, 
'PersonFamilyBackground for ' + cast( dp.PersonID as nvarchar)     AS PersonFamilyBackground, 
dp.EmploymentStatusID, 
dp.PersonEmploymentStatusHoursPerWeek, 
dp.EmploymentHistoryID, 
dp.PersonLastEmploymentDate, 
'PersonEmploymentBackground for ' + cast( dp.PersonID as nvarchar)     AS PersonEmploymentBackground, 
'PersonReferenceNumber for ' + cast( dp.PersonID as nvarchar)     AS PersonReferenceNumber, 
dp.PersonUDF1, dp.PersonUDF2, dp.PersonUDF3, dp.PersonUDF4, dp.PersonUDF5, 
'PersonSocialBackground for ' + cast( dp.PersonID as nvarchar)     AS PersonSocialBackground, 
'PersonTreatmentBackground for ' + cast( dp.PersonID as nvarchar)     AS PersonTreatmentBackground, 
dp.LivingSituationID, 
dp.PersonServiceUserConsent, dp.PrimaryCarerID, dp.Ethnicity1ID, dp.Ethnicity2ID, dp.Ethnicity3ID, dp.Ethnicity4ID, dp.Ethnicity5ID, dp.PersonIsPrivate, dp.PersonFosterChildrenCapacity, dp.PersonPreferedFosterCareService, 

'PersonMadePrivateOrPublicReason for ' + cast( dp.PersonID as nvarchar)     AS PersonMadePrivateOrPublicReason, 

dp.PersonMadePrivateOrPublicDate, dp.MadePrivateOrPublicUserId, dp.GenderIdentityId
FROM  dl.DimPerson dp

GO

